language: node_js
node_js:
  - "6"

stages:
  - test
  # - release

cache:
  directories:
    - node_modules

env:
  global:
    - LAUNCHER=Node

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libgif-dev libpng-dev libjpeg8-dev libpango1.0-dev libcairo2-dev

install: npm install

script: 'testem ci --port 8080 -f testem.json -l $LAUNCHER'

jobs:
  include:
    - stage: test
      before_install: skip
      script: 'npm run lint && npm run lint_tests'
    - stage: test
      env: LAUNCHER=Chrome
      before_install: skip
    - stage: test
      env: LAUNCHER=Firefox
      before_install: skip
    - stage: test
      node_js: "9"
    - stage: test
      node_js: "8"
    - stage: test
      node_js: "6"
    - stage: test
      node_js: "4"

dist: trusty
